/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "assignment.h"

void
generate_assignment(FILE *stream, struct assignment_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", (record->name ? record->name : ""));
  fprintf (stream, "%s", " = ");
  fprintf (stream, "%s", (record->val ? record->val : ""));
  fprintf (stream, "%s", ";");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_assignment(FILE *stream, unsigned int indent, const char *name, const char *val)
{
  struct assignment_gen_struct record;
  
  record.name = name;
  record.val = val;

  generate_assignment (stream, &record, indent);
}

char *
genstring_assignment(struct assignment_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_assignment (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  if (record->name) strcat (output, record->name);
  strcat (output, " = ");
  if (record->val) strcat (output, record->val);
  strcat (output, ";");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_assignment(unsigned int indent, const char *name, const char *val)
{
  struct assignment_gen_struct record;
  
  record.name = name;
  record.val = val;

  return genstring_assignment (&record, indent);
}

int
strcnt_assignment(struct assignment_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->name ? strlen (record->name) : 0) * 1;
  length += (record->val ? strlen (record->val) : 0) * 1;

  return length + 7;
}

void
init_assignment_gen_struct(struct assignment_gen_struct *record)
{
  record->name = 0;
  record->val = 0;
}

