/*
 * File automatically generated by
 * gengen 1.4 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef ASSIGNMENT_GEN_STRUCT_H
#define ASSIGNMENT_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct assignment_gen_struct
{
  const char *name;
  const char *val;
};

void
generate_assignment(FILE *stream, struct assignment_gen_struct *record, unsigned int indent);

void
generatep_assignment(FILE *stream, unsigned int indent, const char *name, const char *val);

char *
genstring_assignment(struct assignment_gen_struct *record, unsigned int indent);

char *
genstringp_assignment(unsigned int indent, const char *name, const char *val);

int
strcnt_assignment(struct assignment_gen_struct *record, unsigned int indent);

void
init_assignment_gen_struct(struct assignment_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // ASSIGNMENT_GEN_STRUCT_H
