/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef CRC_CFG_DECL_GEN_STRUCT_H
#define CRC_CFG_DECL_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct crc_cfg_decl_gen_struct
{
  const char *crc;
  const char *packet;
  const char *prefix;
};

void
generate_crc_cfg_decl(FILE *stream, struct crc_cfg_decl_gen_struct *record, unsigned int indent);

void
generatep_crc_cfg_decl(FILE *stream, unsigned int indent, const char *crc, const char *packet, const char *prefix);

char *
genstring_crc_cfg_decl(struct crc_cfg_decl_gen_struct *record, unsigned int indent);

char *
genstringp_crc_cfg_decl(unsigned int indent, const char *crc, const char *packet, const char *prefix);

int
strcnt_crc_cfg_decl(struct crc_cfg_decl_gen_struct *record, unsigned int indent);

void
init_crc_cfg_decl_gen_struct(struct crc_cfg_decl_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // CRC_CFG_DECL_GEN_STRUCT_H
