/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "crc_cfg_decl.h"

void
generate_crc_cfg_decl(FILE *stream, struct crc_cfg_decl_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", (record->prefix ? record->prefix : ""));
  fprintf (stream, "%s", "_crc_cfg_t ");
  fprintf (stream, "%s", (record->packet ? record->packet : ""));
  fprintf (stream, "%s", "_");
  fprintf (stream, "%s", (record->crc ? record->crc : ""));
  fprintf (stream, "%s", ";");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_crc_cfg_decl(FILE *stream, unsigned int indent, const char *crc, const char *packet, const char *prefix)
{
  struct crc_cfg_decl_gen_struct record;
  
  record.crc = crc;
  record.packet = packet;
  record.prefix = prefix;

  generate_crc_cfg_decl (stream, &record, indent);
}

char *
genstring_crc_cfg_decl(struct crc_cfg_decl_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_crc_cfg_decl (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  if (record->prefix) strcat (output, record->prefix);
  strcat (output, "_crc_cfg_t ");
  if (record->packet) strcat (output, record->packet);
  strcat (output, "_");
  if (record->crc) strcat (output, record->crc);
  strcat (output, ";");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_crc_cfg_decl(unsigned int indent, const char *crc, const char *packet, const char *prefix)
{
  struct crc_cfg_decl_gen_struct record;
  
  record.crc = crc;
  record.packet = packet;
  record.prefix = prefix;

  return genstring_crc_cfg_decl (&record, indent);
}

int
strcnt_crc_cfg_decl(struct crc_cfg_decl_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->prefix ? strlen (record->prefix) : 0) * 1;
  length += (record->packet ? strlen (record->packet) : 0) * 1;
  length += (record->crc ? strlen (record->crc) : 0) * 1;

  return length + 16;
}

void
init_crc_cfg_decl_gen_struct(struct crc_cfg_decl_gen_struct *record)
{
  record->crc = 0;
  record->packet = 0;
  record->prefix = 0;
}

