/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef DYNAMIC_PACKET_TEST_FUNCTION_GEN_STRUCT_H
#define DYNAMIC_PACKET_TEST_FUNCTION_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct dynamic_packet_test_function_gen_struct
{
  const char *name;
  int packet_size;
  const char *prefix;
  const char *test_frame_dynamic;
};

extern void generate_test_frame_dynamic(FILE *stream, struct dynamic_packet_test_function_gen_struct *record, unsigned int indent);


void
generate_dynamic_packet_test_function(FILE *stream, struct dynamic_packet_test_function_gen_struct *record, unsigned int indent);

void
generatep_dynamic_packet_test_function(FILE *stream, unsigned int indent, const char *name, int packet_size, const char *prefix, const char *test_frame_dynamic);

char *
genstring_dynamic_packet_test_function(struct dynamic_packet_test_function_gen_struct *record, unsigned int indent);

char *
genstringp_dynamic_packet_test_function(unsigned int indent, const char *name, int packet_size, const char *prefix, const char *test_frame_dynamic);

int
strcnt_dynamic_packet_test_function(struct dynamic_packet_test_function_gen_struct *record, unsigned int indent);

void
init_dynamic_packet_test_function_gen_struct(struct dynamic_packet_test_function_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // DYNAMIC_PACKET_TEST_FUNCTION_GEN_STRUCT_H
