/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef FIXED_PACKET_TEST_FUNCTION_IMPL_GEN_STRUCT_H
#define FIXED_PACKET_TEST_FUNCTION_IMPL_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct fixed_packet_test_function_impl_gen_struct
{
  const char *name;
  int packet_size;
  const char *prefix;
  const char *test_frame_fixed;
};

extern void generate_test_frame_fixed(FILE *stream, struct fixed_packet_test_function_impl_gen_struct *record, unsigned int indent);


void
generate_fixed_packet_test_function_impl(FILE *stream, struct fixed_packet_test_function_impl_gen_struct *record, unsigned int indent);

void
generatep_fixed_packet_test_function_impl(FILE *stream, unsigned int indent, const char *name, int packet_size, const char *prefix, const char *test_frame_fixed);

char *
genstring_fixed_packet_test_function_impl(struct fixed_packet_test_function_impl_gen_struct *record, unsigned int indent);

char *
genstringp_fixed_packet_test_function_impl(unsigned int indent, const char *name, int packet_size, const char *prefix, const char *test_frame_fixed);

int
strcnt_fixed_packet_test_function_impl(struct fixed_packet_test_function_impl_gen_struct *record, unsigned int indent);

void
init_fixed_packet_test_function_impl_gen_struct(struct fixed_packet_test_function_impl_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // FIXED_PACKET_TEST_FUNCTION_IMPL_GEN_STRUCT_H
