/*
 * File automatically generated by
 * gengen 1.4 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef FIXED_PACKET_NO_FRAME_TEST_FUNCTION_GEN_STRUCT_H
#define FIXED_PACKET_NO_FRAME_TEST_FUNCTION_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct fixed_packet_no_frame_test_function_gen_struct
{
  const char *name;
  int packet_size;
  const char *prefix;
};

void
generate_fixed_packet_no_frame_test_function(FILE *stream, struct fixed_packet_no_frame_test_function_gen_struct *record, unsigned int indent);

void
generatep_fixed_packet_no_frame_test_function(FILE *stream, unsigned int indent, const char *name, int packet_size, const char *prefix);

char *
genstring_fixed_packet_no_frame_test_function(struct fixed_packet_no_frame_test_function_gen_struct *record, unsigned int indent);

char *
genstringp_fixed_packet_no_frame_test_function(unsigned int indent, const char *name, int packet_size, const char *prefix);

int
strcnt_fixed_packet_no_frame_test_function(struct fixed_packet_no_frame_test_function_gen_struct *record, unsigned int indent);

void
init_fixed_packet_no_frame_test_function_gen_struct(struct fixed_packet_no_frame_test_function_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // FIXED_PACKET_NO_FRAME_TEST_FUNCTION_GEN_STRUCT_H
