/*
 * File automatically generated by
 * gengen 1.4 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "function_call.h"

void
generate_function_call(FILE *stream, struct function_call_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", (record->function ? record->function : ""));
  fprintf (stream, "%s", "(");
  fprintf (stream, "%s", (record->params ? record->params : ""));
  fprintf (stream, "%s", ");");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_function_call(FILE *stream, unsigned int indent, const char *function, const char *params)
{
  struct function_call_gen_struct record;
  
  record.function = function;
  record.params = params;

  generate_function_call (stream, &record, indent);
}

char *
genstring_function_call(struct function_call_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_function_call (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  if (record->function) strcat (output, record->function);
  strcat (output, "(");
  if (record->params) strcat (output, record->params);
  strcat (output, ");");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_function_call(unsigned int indent, const char *function, const char *params)
{
  struct function_call_gen_struct record;
  
  record.function = function;
  record.params = params;

  return genstring_function_call (&record, indent);
}

int
strcnt_function_call(struct function_call_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->function ? strlen (record->function) : 0) * 1;
  length += (record->params ? strlen (record->params) : 0) * 1;

  return length + 6;
}

void
init_function_call_gen_struct(struct function_call_gen_struct *record)
{
  record->function = 0;
  record->params = 0;
}

