/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef FUNCTION_CALL_GEN_STRUCT_H
#define FUNCTION_CALL_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct function_call_gen_struct
{
  const char *function;
  const char *params;
};

void
generate_function_call(FILE *stream, struct function_call_gen_struct *record, unsigned int indent);

void
generatep_function_call(FILE *stream, unsigned int indent, const char *function, const char *params);

char *
genstring_function_call(struct function_call_gen_struct *record, unsigned int indent);

char *
genstringp_function_call(unsigned int indent, const char *function, const char *params);

int
strcnt_function_call(struct function_call_gen_struct *record, unsigned int indent);

void
init_function_call_gen_struct(struct function_call_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // FUNCTION_CALL_GEN_STRUCT_H
