/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef HEADER_GEN_STRUCT_H
#define HEADER_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct header_gen_struct
{
  const char *ifndefname;
  int nro_pipes;
  const char *packets;
  const char *prefix;
  const char *receive_functions;
  const char *send_functions;
};

extern void generate_packets(FILE *stream, struct header_gen_struct *record, unsigned int indent);


extern void generate_receive_functions(FILE *stream, struct header_gen_struct *record, unsigned int indent);


extern void generate_send_functions(FILE *stream, struct header_gen_struct *record, unsigned int indent);


void
generate_header(FILE *stream, struct header_gen_struct *record, unsigned int indent);

void
generatep_header(FILE *stream, unsigned int indent, const char *ifndefname, int nro_pipes, const char *packets, const char *prefix, const char *receive_functions, const char *send_functions);

char *
genstring_header(struct header_gen_struct *record, unsigned int indent);

char *
genstringp_header(unsigned int indent, const char *ifndefname, int nro_pipes, const char *packets, const char *prefix, const char *receive_functions, const char *send_functions);

int
strcnt_header(struct header_gen_struct *record, unsigned int indent);

void
init_header_gen_struct(struct header_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // HEADER_GEN_STRUCT_H
