/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "header.h"


static void
generate_string(const char *s, FILE *stream, unsigned int indent)
{
  const char *sub = s;
  char *indent_str;
  unsigned int i;

  if (!indent || strchr (s, '\n') == 0)
    {
      fprintf (stream, "%s", s);
      return;
    }

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  while ( (sub=strchr (s, '\n')) != 0 )
    {
      fwrite (s, sizeof(char), (sub-s)+1, stream);
      s = sub+1;
      if (s[0])
        fprintf (stream, "%s", indent_str);
    }
  if (s[0])
    fwrite (s, sizeof(char), strlen (s), stream);

  free (indent_str);
}

void
generate_header(FILE *stream, struct header_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", "#ifndef ");
  generate_string ((record->ifndefname ? record->ifndefname : ""), stream, indent + strlen (indent_str));
  fprintf (stream, "%s", "_H");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#define ");
  generate_string ((record->ifndefname ? record->ifndefname : ""), stream, indent + strlen (indent_str));
  fprintf (stream, "%s", "_H");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "/* If we use autoconf.  */");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#ifdef HAVE_CONFIG_H");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#include \"config.h\"");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#endif");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#include <stdint.h>");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#ifdef __cplusplus");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "extern \"C\" {");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#endif /* __cplusplus */");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "struct ");
  generate_string ((record->args_info ? record->args_info : ""), stream, indent + strlen (indent_str));
  fprintf (stream, "%s", " {");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "    int test;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "};");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "struct ");
  generate_string ((record->parser_name ? record->parser_name : ""), stream, indent + strlen (indent_str));
  fprintf (stream, "%s", "_params {");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "    int override;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "    int initialize;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "    int check_required;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "    int check_ambiguity;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "    int print_errors;");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "};");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "int ");
  generate_string ((record->parser_name ? record->parser_name : ""), stream, indent + strlen (indent_str));
  fprintf (stream, "%s", "_init();");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#ifdef __cplusplus");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "}");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#endif /* __cplusplus */");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "#endif /* ");
  generate_string ((record->ifndefname ? record->ifndefname : ""), stream, indent + strlen (indent_str));
  fprintf (stream, "%s", "_H */");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_header(FILE *stream, unsigned int indent, const char *args_info, const char *ifndefname, const char *parser_name)
{
  struct header_gen_struct record;
  
  record.args_info = args_info;
  record.ifndefname = ifndefname;
  record.parser_name = parser_name;

  generate_header (stream, &record, indent);
}

char *
genstring_header(struct header_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_header (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  strcat (output, "#ifndef ");
  if (record->ifndefname) strcat (output, record->ifndefname);
  strcat (output, "_H");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#define ");
  if (record->ifndefname) strcat (output, record->ifndefname);
  strcat (output, "_H");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "/* If we use autoconf.  */");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#ifdef HAVE_CONFIG_H");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#include \"config.h\"");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#endif");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#include <stdint.h>");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#ifdef __cplusplus");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "extern \"C\" {");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#endif /* __cplusplus */");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "struct ");
  if (record->args_info) strcat (output, record->args_info);
  strcat (output, " {");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "    int test;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "};");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "struct ");
  if (record->parser_name) strcat (output, record->parser_name);
  strcat (output, "_params {");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "    int override;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "    int initialize;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "    int check_required;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "    int check_ambiguity;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "    int print_errors;");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "};");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "int ");
  if (record->parser_name) strcat (output, record->parser_name);
  strcat (output, "_init();");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#ifdef __cplusplus");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "}");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#endif /* __cplusplus */");
  strcat (output, "\n");
  strcat (output, indent_str);
  strcat (output, "#endif /* ");
  if (record->ifndefname) strcat (output, record->ifndefname);
  strcat (output, "_H */");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_header(unsigned int indent, const char *args_info, const char *ifndefname, const char *parser_name)
{
  struct header_gen_struct record;
  
  record.args_info = args_info;
  record.ifndefname = ifndefname;
  record.parser_name = parser_name;

  return genstring_header (&record, indent);
}

int
strcnt_header(struct header_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->ifndefname ? strlen (record->ifndefname) : 0) * 3;
  length += (record->args_info ? strlen (record->args_info) : 0) * 1;
  length += (record->parser_name ? strlen (record->parser_name) : 0) * 2;

  return length + 476;
}

void
init_header_gen_struct(struct header_gen_struct *record)
{
  record->args_info = 0;
  record->ifndefname = 0;
  record->parser_name = 0;
}

