/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef HEADER_GEN_STRUCT_H
#define HEADER_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct header_gen_struct
{
  const char *args_info;
  const char *ifndefname;
  const char *parser_name;
};

void
generate_header(FILE *stream, struct header_gen_struct *record, unsigned int indent);

void
generatep_header(FILE *stream, unsigned int indent, const char *args_info, const char *ifndefname, const char *parser_name);

char *
genstring_header(struct header_gen_struct *record, unsigned int indent);

char *
genstringp_header(unsigned int indent, const char *args_info, const char *ifndefname, const char *parser_name);

int
strcnt_header(struct header_gen_struct *record, unsigned int indent);

void
init_header_gen_struct(struct header_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // HEADER_GEN_STRUCT_H
