/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef RECEIVE_CALLBACK_DECL_GEN_STRUCT_H
#define RECEIVE_CALLBACK_DECL_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct receive_callback_decl_gen_struct
{
  const char *packet_name;
  const char *prefix;
  const char *type;
};

void
generate_receive_callback_decl(FILE *stream, struct receive_callback_decl_gen_struct *record, unsigned int indent);

void
generatep_receive_callback_decl(FILE *stream, unsigned int indent, const char *packet_name, const char *prefix, const char *type);

char *
genstring_receive_callback_decl(struct receive_callback_decl_gen_struct *record, unsigned int indent);

char *
genstringp_receive_callback_decl(unsigned int indent, const char *packet_name, const char *prefix, const char *type);

int
strcnt_receive_callback_decl(struct receive_callback_decl_gen_struct *record, unsigned int indent);

void
init_receive_callback_decl_gen_struct(struct receive_callback_decl_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // RECEIVE_CALLBACK_DECL_GEN_STRUCT_H
