/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "receive_callback.h"

void
generate_receive_callback(FILE *stream, struct receive_callback_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", "extern ");
  fprintf (stream, "%s", (record->type ? record->type : ""));
  fprintf (stream, "%s", " ");
  fprintf (stream, "%s", (record->prefix ? record->prefix : ""));
  fprintf (stream, "%s", "_");
  fprintf (stream, "%s", (record->packet_name ? record->packet_name : ""));
  fprintf (stream, "%s", "_received(struct ");
  fprintf (stream, "%s", (record->packet_name ? record->packet_name : ""));
  fprintf (stream, "%s", " *packet, void *private_ctx);");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_receive_callback(FILE *stream, unsigned int indent, const char *packet_name, const char *prefix, const char *type)
{
  struct receive_callback_gen_struct record;
  
  record.packet_name = packet_name;
  record.prefix = prefix;
  record.type = type;

  generate_receive_callback (stream, &record, indent);
}

char *
genstring_receive_callback(struct receive_callback_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_receive_callback (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  strcat (output, "extern ");
  if (record->type) strcat (output, record->type);
  strcat (output, " ");
  if (record->prefix) strcat (output, record->prefix);
  strcat (output, "_");
  if (record->packet_name) strcat (output, record->packet_name);
  strcat (output, "_received(struct ");
  if (record->packet_name) strcat (output, record->packet_name);
  strcat (output, " *packet, void *private_ctx);");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_receive_callback(unsigned int indent, const char *packet_name, const char *prefix, const char *type)
{
  struct receive_callback_gen_struct record;
  
  record.packet_name = packet_name;
  record.prefix = prefix;
  record.type = type;

  return genstring_receive_callback (&record, indent);
}

int
strcnt_receive_callback(struct receive_callback_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->type ? strlen (record->type) : 0) * 1;
  length += (record->prefix ? strlen (record->prefix) : 0) * 1;
  length += (record->packet_name ? strlen (record->packet_name) : 0) * 2;

  return length + 58;
}

void
init_receive_callback_gen_struct(struct receive_callback_gen_struct *record)
{
  record->packet_name = 0;
  record->prefix = 0;
  record->type = 0;
}

