/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "send_func_impl.h"


static void
generate_string(const char *s, FILE *stream, unsigned int indent)
{
  const char *sub = s;
  char *indent_str;
  unsigned int i;

  if (!indent || strchr (s, '\n') == 0)
    {
      fprintf (stream, "%s", s);
      return;
    }

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  while ( (sub=strchr (s, '\n')) != 0 )
    {
      fwrite (s, sizeof(char), (sub-s)+1, stream);
      s = sub+1;
      if (s[0])
        fprintf (stream, "%s", indent_str);
    }
  if (s[0])
    fwrite (s, sizeof(char), strlen (s), stream);

  free (indent_str);
}

void
generate_send_func_impl(FILE *stream, struct send_func_impl_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", "int ");
  fprintf (stream, "%s", (record->prefix ? record->prefix : ""));
  fprintf (stream, "%s", "_");
  fprintf (stream, "%s", (record->packet_name ? record->packet_name : ""));
  fprintf (stream, "%s", "_send(struct ");
  fprintf (stream, "%s", (record->packet_name ? record->packet_name : ""));
  fprintf (stream, "%s", " *packet) {");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);
  indent = 4;
  if (record->send_func)
    generate_string (record->send_func, stream, indent + strlen (indent_str));
  else
    generate_send_func (stream, record, indent + strlen (indent_str));
  indent = 0;
  fprintf (stream, "%s", indent_str);
  fprintf (stream, "%s", "}");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_send_func_impl(FILE *stream, unsigned int indent, const char *packet_name, const char *prefix, const char *send_func)
{
  struct send_func_impl_gen_struct record;
  
  record.packet_name = packet_name;
  record.prefix = prefix;
  record.send_func = send_func;

  generate_send_func_impl (stream, &record, indent);
}

char *
genstring_send_func_impl(struct send_func_impl_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_send_func_impl (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  strcat (output, "int ");
  if (record->prefix) strcat (output, record->prefix);
  strcat (output, "_");
  if (record->packet_name) strcat (output, record->packet_name);
  strcat (output, "_send(struct ");
  if (record->packet_name) strcat (output, record->packet_name);
  strcat (output, " *packet) {");
  strcat (output, "\n");
  strcat (output, indent_str);
  if (record->send_func) strcat (output, record->send_func);
  strcat (output, indent_str);
  strcat (output, "}");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_send_func_impl(unsigned int indent, const char *packet_name, const char *prefix, const char *send_func)
{
  struct send_func_impl_gen_struct record;
  
  record.packet_name = packet_name;
  record.prefix = prefix;
  record.send_func = send_func;

  return genstring_send_func_impl (&record, indent);
}

int
strcnt_send_func_impl(struct send_func_impl_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->prefix ? strlen (record->prefix) : 0) * 1;
  length += (record->packet_name ? strlen (record->packet_name) : 0) * 2;
  length += (record->send_func ? strlen (record->send_func) : 0) * 1;

  return length + 38;
}

void
init_send_func_impl_gen_struct(struct send_func_impl_gen_struct *record)
{
  record->packet_name = 0;
  record->prefix = 0;
  record->send_func = 0;
}

