/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef SEND_FUNC_IMPL_GEN_STRUCT_H
#define SEND_FUNC_IMPL_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct send_func_impl_gen_struct
{
  const char *packet_name;
  const char *prefix;
  const char *send_func;
};

extern void generate_send_func(FILE *stream, struct send_func_impl_gen_struct *record, unsigned int indent);


void
generate_send_func_impl(FILE *stream, struct send_func_impl_gen_struct *record, unsigned int indent);

void
generatep_send_func_impl(FILE *stream, unsigned int indent, const char *packet_name, const char *prefix, const char *send_func);

char *
genstring_send_func_impl(struct send_func_impl_gen_struct *record, unsigned int indent);

char *
genstringp_send_func_impl(unsigned int indent, const char *packet_name, const char *prefix, const char *send_func);

int
strcnt_send_func_impl(struct send_func_impl_gen_struct *record, unsigned int indent);

void
init_send_func_impl_gen_struct(struct send_func_impl_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // SEND_FUNC_IMPL_GEN_STRUCT_H
