/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef SOURCE_SKELETON_GEN_STRUCT_H
#define SOURCE_SKELETON_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct source_skeleton_gen_struct
{
  const char *cmd_options;
  const char *genpacket;
  const char *ifndefname;
  const char *prefix;
  const char *receive_buffers;
  const char *send_buffers;
  const char *version;
};

extern void generate_receive_buffers(FILE *stream, struct source_skeleton_gen_struct *record, unsigned int indent);


extern void generate_send_buffers(FILE *stream, struct source_skeleton_gen_struct *record, unsigned int indent);


void
generate_source_skeleton(FILE *stream, struct source_skeleton_gen_struct *record, unsigned int indent);

void
generatep_source_skeleton(FILE *stream, unsigned int indent, const char *cmd_options, const char *genpacket, const char *ifndefname, const char *prefix, const char *receive_buffers, const char *send_buffers, const char *version);

char *
genstring_source_skeleton(struct source_skeleton_gen_struct *record, unsigned int indent);

char *
genstringp_source_skeleton(unsigned int indent, const char *cmd_options, const char *genpacket, const char *ifndefname, const char *prefix, const char *receive_buffers, const char *send_buffers, const char *version);

int
strcnt_source_skeleton(struct source_skeleton_gen_struct *record, unsigned int indent);

void
init_source_skeleton_gen_struct(struct source_skeleton_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // SOURCE_SKELETON_GEN_STRUCT_H
