/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef STRUCTS_GEN_STRUCT_H
#define STRUCTS_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct structs_gen_struct
{
  const char *struct_member_method;
  const char *struct_name;
};

extern void generate_struct_member_method(FILE *stream, struct structs_gen_struct *record, unsigned int indent);


void
generate_structs(FILE *stream, struct structs_gen_struct *record, unsigned int indent);

void
generatep_structs(FILE *stream, unsigned int indent, const char *struct_member_method, const char *struct_name);

char *
genstring_structs(struct structs_gen_struct *record, unsigned int indent);

char *
genstringp_structs(unsigned int indent, const char *struct_member_method, const char *struct_name);

int
strcnt_structs(struct structs_gen_struct *record, unsigned int indent);

void
init_structs_gen_struct(struct structs_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // STRUCTS_GEN_STRUCT_H
