/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TOOLS_SRC_GEN_STRUCT_H
#define TOOLS_SRC_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct tools_src_gen_struct
{
  const char *prefix;
};

void
generate_tools_src(FILE *stream, struct tools_src_gen_struct *record, unsigned int indent);

void
generatep_tools_src(FILE *stream, unsigned int indent, const char *prefix);

char *
genstring_tools_src(struct tools_src_gen_struct *record, unsigned int indent);

char *
genstringp_tools_src(unsigned int indent, const char *prefix);

int
strcnt_tools_src(struct tools_src_gen_struct *record, unsigned int indent);

void
init_tools_src_gen_struct(struct tools_src_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // TOOLS_SRC_GEN_STRUCT_H
