/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef TOOLS_HDR_GEN_STRUCT_H
#define TOOLS_HDR_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct tools_hdr_gen_struct
{
  const char *ifndefname;
  short modulo;
  const char *prefix;
};

void
generate_tools_hdr(FILE *stream, struct tools_hdr_gen_struct *record, unsigned int indent);

void
generatep_tools_hdr(FILE *stream, unsigned int indent, const char *ifndefname, short modulo, const char *prefix);

char *
genstring_tools_hdr(struct tools_hdr_gen_struct *record, unsigned int indent);

char *
genstringp_tools_hdr(unsigned int indent, const char *ifndefname, short modulo, const char *prefix);

int
strcnt_tools_hdr(struct tools_hdr_gen_struct *record, unsigned int indent);

void
init_tools_hdr_gen_struct(struct tools_hdr_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // TOOLS_HDR_GEN_STRUCT_H
