/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef VAR_DECLARATION_GEN_STRUCT_H
#define VAR_DECLARATION_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct var_declaration_gen_struct
{
  short array;
  const char *member_name;
  short pointer;
  int size;
  const char *type;
};

void
generate_var_declaration(FILE *stream, struct var_declaration_gen_struct *record, unsigned int indent);

void
generatep_var_declaration(FILE *stream, unsigned int indent, short array, const char *member_name, short pointer, int size, const char *type);

char *
genstring_var_declaration(struct var_declaration_gen_struct *record, unsigned int indent);

char *
genstringp_var_declaration(unsigned int indent, short array, const char *member_name, short pointer, int size, const char *type);

int
strcnt_var_declaration(struct var_declaration_gen_struct *record, unsigned int indent);

void
init_var_declaration_gen_struct(struct var_declaration_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // VAR_DECLARATION_GEN_STRUCT_H
