/*
 * File automatically generated by
 * gengen  by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef WRITE_DATA_GEN_STRUCT_H
#define WRITE_DATA_GEN_STRUCT_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct write_data_gen_struct
{
  short array;
  const char *name;
  int pipe;
  const char *prefix;
  int size;
};

void
generate_write_data(FILE *stream, struct write_data_gen_struct *record, unsigned int indent);

void
generatep_write_data(FILE *stream, unsigned int indent, short array, const char *name, int pipe, const char *prefix, int size);

char *
genstring_write_data(struct write_data_gen_struct *record, unsigned int indent);

char *
genstringp_write_data(unsigned int indent, short array, const char *name, int pipe, const char *prefix, int size);

int
strcnt_write_data(struct write_data_gen_struct *record, unsigned int indent);

void
init_write_data_gen_struct(struct write_data_gen_struct *record);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif // WRITE_DATA_GEN_STRUCT_H
