/*
 * File automatically generated by
 * gengen 1.4.3rc by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#include "write_data.h"


static char *
int_to_string(int i)
{
  static char buffer[256];

  snprintf (buffer, 255, "%d", i);

  return buffer;
}

void
generate_write_data(FILE *stream, struct write_data_gen_struct *record, unsigned int indent)
{
  char *indent_str;
  unsigned int i;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';
  indent = 0;

  fprintf (stream, "%s", "write(");
  fprintf (stream, "%s", (record->prefix ? record->prefix : ""));
  fprintf (stream, "%s", "_ctx.params.wfds[");
  fprintf (stream, "%d", record->pipe);
  fprintf (stream, "%s", "], &packet->");
  fprintf (stream, "%s", (record->name ? record->name : ""));
  fprintf (stream, "%s", ", ");
  fprintf (stream, "%d", record->size);
  fprintf (stream, "%s", ");");
  fprintf (stream, "%s", "\n");
  fprintf (stream, "%s", indent_str);

  free (indent_str);
}

void
generatep_write_data(FILE *stream, unsigned int indent, const char *name, int pipe, const char *prefix, int size)
{
  struct write_data_gen_struct record;
  
  record.name = name;
  record.pipe = pipe;
  record.prefix = prefix;
  record.size = size;

  generate_write_data (stream, &record, indent);
}

char *
genstring_write_data(struct write_data_gen_struct *record, unsigned int indent)
{
  char *indent_str, *output;
  unsigned int i;
  int len;

  indent_str = (char *) malloc (indent + 1);
  for (i = 0; i < indent; ++i)
    indent_str[i] = ' ';
  indent_str[indent] = '\0';

  len = strcnt_write_data (record, indent);
  output = (char *) malloc (len + 1);
  output[0] = '\0';

  strcat (output, "write(");
  if (record->prefix) strcat (output, record->prefix);
  strcat (output, "_ctx.params.wfds[");
  strcat (output, int_to_string (record->pipe));
  strcat (output, "], &packet->");
  if (record->name) strcat (output, record->name);
  strcat (output, ", ");
  strcat (output, int_to_string (record->size));
  strcat (output, ");");
  strcat (output, "\n");
  strcat (output, indent_str);

  free (indent_str);

  return output;
}

char *
genstringp_write_data(unsigned int indent, const char *name, int pipe, const char *prefix, int size)
{
  struct write_data_gen_struct record;
  
  record.name = name;
  record.pipe = pipe;
  record.prefix = prefix;
  record.size = size;

  return genstring_write_data (&record, indent);
}

int
strcnt_write_data(struct write_data_gen_struct *record, unsigned int indent)
{
  int length = 0;
  
  length += (record->prefix ? strlen (record->prefix) : 0) * 1;
  length += strlen (int_to_string (record->pipe)) * 1;
  length += (record->name ? strlen (record->name) : 0) * 1;
  length += strlen (int_to_string (record->size)) * 1;

  return length + 42;
}

void
init_write_data_gen_struct(struct write_data_gen_struct *record)
{
  record->name = 0;
  record->pipe = 0;
  record->prefix = 0;
  record->size = 0;
}

